# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Smart&Nimble Blog
author: Dmitri Lihhatsov
email: dmitri@smartandnimble.com
description: > # this means to ignore newlines until "baseurl:"
  On the quest of pursuing interdisciplinary knowledge and sharing my
  findings with the world. I write about artificial intelligence, IT,
  psychology and personal development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dimileeh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dimileeh
github_username:  dimileeh

minima:
  social_links:
    twitter: dimileeh
    facebook: dmitri.lihhatsov
    instagram: dimileeh
    youtube_channel: UCT_Yp-WuZU9US9m6YOCFWng
    linkedin: dmitrilihhatsov

show_excerpts: true

google_analytics: UA-100590015-1

comments:
  provider: "disqus"
disqus:
  shortname: "dmitri-lihhatsov-blog"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

